# Numpy Module

In [1]:
import numpy as np

In [3]:
data1 = [1,2,3,4,5]
a1 = np.array(data1,dtype=float)
a1

array([1., 2., 3., 4., 5.])

In [4]:
a2 = np.array([0.5,2,0.01,6])
a2

array([0.5 , 2.  , 0.01, 6.  ])

In [5]:
print(type(a2))     # 내부 데이터 타입은 알려주지 않음
print(a2.dtype)

<class 'numpy.ndarray'>
float64


In [6]:
a3 = np.arange(0,10,2)
a3

array([0, 2, 4, 6, 8])

## reshape

In [8]:
data2 = np.arange(12).reshape(-1,3)
data2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## linspace

In [11]:
data3 = np.linspace(0,np.pi,12).reshape(-1,4)
data3

array([[0.        , 0.28559933, 0.57119866, 0.856798  ],
       [1.14239733, 1.42799666, 1.71359599, 1.99919533],
       [2.28479466, 2.57039399, 2.85599332, 3.14159265]])

## 난수 배열 생성하기

In [12]:
rand_num = np.random.rand(2,3)
rand_num

array([[0.97459968, 0.34565068, 0.83746666],
       [0.65008698, 0.64109789, 0.34581287]])

In [14]:
rand_num = np.random.randint(10,size=(3,4))
rand_num

array([[9, 2, 6, 5],
       [8, 7, 7, 3],
       [7, 2, 0, 1]])

In [16]:
one_rand_num = np.random.randint(15)
one_rand_num

14

## astype

In [19]:
num_arr = np.array(["1","234","2143231"])
print(num_arr.dtype)
num_arr = num_arr.astype("f")
num_arr

<U7


array([1.000000e+00, 2.340000e+02, 2.143231e+06], dtype=float32)

# practice

In [20]:
# a = [1,2,3,4] 리스트를 float 타입 배열 A를 만들기
a = [1,2,3,4]
A = np.array(a,dtype=float)
A

array([1., 2., 3., 4.])

In [21]:
# b =[True, False, True] 불타입 리스트를 배열B로 만들고 정수형으로 출력하기
b = [True,False,True]
B = np.array(b,dtype=int)
B

array([1, 0, 1])

In [22]:
c = [[1,2,3],[4,5,6]]
C = np.array(c)
C

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
C = np.arange(1,7).reshape(2,3)
C

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# [0,1] 범위의 난수로 4 x 5 배열 R과 2~100사이의 정수 중 4 x 5의 난수 배
# 열 G를 생성 하기 (0이상 1미만)
R = np.random.rand(4,5)
print(R)
G = np.random.randint(2,100,size=(4,5))
print(G)

[[0.13616484 0.75512021 0.8149638  0.54897451 0.12491189]
 [0.12425817 0.75010141 0.85114614 0.84224353 0.12180009]
 [0.72008466 0.25883188 0.4868518  0.12176765 0.04759429]
 [0.90464643 0.74480841 0.39264941 0.19138392 0.94621865]]
[[46 61 27 66 64]
 [78 63 34 94 67]
 [74 75 31 44 32]
 [58 83 10 85 68]]


In [31]:
R_mean = R.mean()
G_mean = G.mean()
print(R_mean, G_mean)

0.4942260850588222 58.0


In [35]:
max = (R+G).max()
max

94.84224352882474